### ISSUE TITLE
Java 11 : jaxb removed, need to add the dependency explicitly

### ISSUE THREAD

**Issue by juliender** [playframework/play-soap#101]
Hi

I just tried to upgrade my Play Scala project (which has dependency to play-soap)  to Java 11.
I have this error `java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException`

I tried adding `libraryDependencies += "javax.xml.bind" % "jaxb-api" % "2.3.1"`
Because the library has been removed in Java 11.

But the error still appears, maybe the solution is to add the dependency in play-soap.

`[info] Processing WSDL: https://api.mondialrelay.com/Web_Services.asmx?wsdl
[error] java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
[error] 	at org.apache.cxf.tools.wsdlto.WSDLToJava.<init>(WSDLToJava.java:48)
[error] 	at play.soap.sbtplugin.SbtWsdl$.$anonfun$wsdlToCodeTask$4(SbtWsdl.scala:216)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:941)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:941)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error] 	at play.soap.sbtplugin.SbtWsdl$.$anonfun$wsdlToCodeTask$3(SbtWsdl.scala:189)
[error] 	at com.typesafe.sbt.web.incremental.package$.syncIncremental(package.scala:228)
[error] 	at play.soap.sbtplugin.SbtWsdl$.$anonfun$wsdlToCodeTask$2(SbtWsdl.scala:187)
[error] 	at play.soap.sbtplugin.SbtWsdl$.withContextClassLoader(SbtWsdl.scala:275)
[error] 	at play.soap.sbtplugin.SbtWsdl$.$anonfun$wsdlToCodeTask$1(SbtWsdl.scala:184)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:280)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:289)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:280)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by ihostage** [comment]
Hi, @juliender !
Can you share a project for reproducing?
Are you sure, that you configure `libraryDependencies` for plugins, not for the project?

**Comment by juliender** [comment]
Thanks for your reply

I got it to work by adding dependencies in both `plugins.sbt` and `build.sbt` (see below)

I dont think every library is required, but it takes a very long time to test that.
For now I am not going on with java 11.

**plugins.sbt**
    
    // https://mvnrepository.com/artifact/javax.xml.ws/jaxws-api
    //libraryDependencies += "javax.xml.ws" % "jaxws-api" % "2.3.1"
    libraryDependencies += "javax.activation" % "activation" % "1.1"
    libraryDependencies += "org.glassfish.jaxb" % "jaxb-runtime" % "2.3.0"
    
    
    // https://mvnrepository.com/artifact/javax.xml.bind/jaxb-api
    libraryDependencies += "javax.xml.bind" % "jaxb-api" % "2.3.1"
    
    // https://github.com/stagemonitor/stagemonitor/issues/455
    libraryDependencies += "com.sun.xml.ws" % "jaxws-ri" % "2.3.2"
    // https://mvnrepository.com/artifact/com.sun.xml.bind/jaxb-core
    //libraryDependencies += "com.sun.xml.bind" % "jaxb-core" % "2.3.0.1"
    // https://mvnrepository.com/artifact/com.sun.xml.bind/jaxb-impl
    //libraryDependencies += "com.sun.xml.bind" % "jaxb-impl" % "2.3.2"
    
    // https://mvnrepository.com/artifact/javax.xml.soap/javax.xml.soap-api
    libraryDependencies += "javax.xml.soap" % "javax.xml.soap-api" % "1.4.0"
    

**build.sbt**

    // https://mvnrepository.com/artifact/javax.xml.bind/jaxb-api
    libraryDependencies += "javax.xml.bind" % "jaxb-api" % "2.3.1"
    // https://mvnrepository.com/artifact/javax.xml.ws/jaxws-api
    //libraryDependencies += "javax.xml.ws" % "jaxws-api" % "2.3.1"
    // https://github.com/stagemonitor/stagemonitor/issues/455
    libraryDependencies += "com.sun.xml.ws" % "jaxws-ri" % "2.3.2"
    // https://mvnrepository.com/artifact/com.sun.xml.bind/jaxb-core
    libraryDependencies += "com.sun.xml.bind" % "jaxb-core" % "2.3.0.1"
    // https://mvnrepository.com/artifact/com.sun.xml.bind/jaxb-impl
    libraryDependencies += "com.sun.xml.bind" % "jaxb-impl" % "2.3.2"
    
    // https://mvnrepository.com/artifact/javax.xml.soap/javax.xml.soap-api
    libraryDependencies += "javax.xml.soap" % "javax.xml.soap-api" % "1.4.0"
    
    libraryDependencies += "javax.activation" % "activation" % "1.1"
    libraryDependencies += "org.glassfish.jaxb" % "jaxb-runtime" % "2.3.0"
