### ISSUE TITLE
SOAP 1.2

### ISSUE THREAD

**Issue by kusmierz** [playframework/play-soap#144]
I couldn't find it in the doc nor in the code... is it possible to send SOAP 1.2 message? As far as I know, to set SOAP 1.2 you have to call `factory.setBindingId(SOAPBinding.SOAP12HTTP_BINDING)`, which is not possible to call outside of a generated class (`PlaySoapClient::createPort` in fact). 

Is there any other way to set it to SOAP 1.2?

**Comment by ihostage** [comment]
Fixed in #145
