### ISSUE TITLE
Release play-soap to a public repository

### ISSUE THREAD

**Issue by adrianmaurer** [playframework/play-soap#20]
Where is this published? I can't resolve it using several repositories.

**Comment by fidato13** [comment]
I am experiencing the same problem to resolve this. Can you suggest on the resolvers please.

**Comment by alexduros** [comment]
As of today, it is working with this resolvers : 

```
resolvers += "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots"
```

**Comment by damianball** [comment]
Hmm, that didn't solve the resolution issue for me either. Could there be something else we're missing?

**Comment by marcospereira** [comment]
What if you add this:

https://github.com/playframework/play-soap#installation

I'm not sure all versions are properly released to this repository though.

**Comment by Fancellu2** [comment]
Maybe try jitpack?

https://jitpack.io/#playframework/play-soap

**Comment by marcospereira** [comment]
It is published here:

https://bintray.com/playframework/sbt-plugin-releases/play-soap/1.1.3#

And here:

https://repo1.maven.org/maven2/com/typesafe/play/play-soap-client_2.11/1.1.3/

So I'm closing this.
