### ISSUE TITLE
Client certificate authentication

### ISSUE THREAD

**Issue by alexduros** [playframework/play-soap#37]
I'm using play-soap to make SOAP requests to a server secured by HTTPS with client certificate authentication.

I can't figure out how to configure my play-soap client to make it using my keystore. 

Do I have to implement access to the keystore with [Handlers](http://downloads.typesafe.com/rp/play-soap/Handlers.html) ?

**Comment by alexduros** [comment]
Ok, finally figure out how to do it with [configuration documentation from Apache CXF](http://cxf.apache.org/docs/configuration.html). 

A little bit ugly but I had to add this dependency to my project : 

```xml
<dependency>
   <groupId>org.springframework</groupId>
   <artifactId>spring-context</artifactId>
   <version>3.0.6.RELEASE</version>  (or most recent supported)
</dependency>
```

And then create an `cxf.xml` file : 

```xml
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:http-conf="http://cxf.apache.org/transports/http/configuration"
       xsi:schemaLocation="http://cxf.apache.org/transports/http/configuration
           http://cxf.apache.org/schemas/configuration/http-conf.xsd
           http://www.springframework.org/schema/beans
           http://www.springframework.org/schema/beans/spring-beans.xsd">
 
  <http-conf:conduit
           name="{urn:ebay:apis:eBLBaseComponents}Shopping.http-conduit">
      <http-conf:client AllowChunking="false"/>
  </http-conf:conduit>
</beans>
```

And then I had be able to provide KeyManager configuration parameters.

**Comment by davidcyp** [comment]
@alexduros did you also sign your soap messages based on the provided keystore?

**Comment by alexduros** [comment]
@davidcyp as far as I remember (I'm not working on this stack anymore so I have forgotten some parts of the issue I faced), I don't think so. It was just about the HTTPS requests but not about the soap message itself. sorry.

**Comment by ihostage** [comment]
@alexduros You can get `HTTPConduit` from source code. For example:
```java
// Load KeyStore (JKS or PKCS12)
KeyStore ks = KeyStore.getInstance("PKCS12");
ks.load(Files.newInputStream(Paths.get("/.../cacerts.pfx")), "password".toCharArray());
final SSLContext sslContext = SSLContexts.custom()
    .loadKeyMaterial(ks, "password".toCharArray())
    .loadTrustMaterial(ks, new TrustSelfSignedStrategy()) // can be another strategy
    .build();
// Configure SSL context for HTTP client
MySoapService service = ...;
PlayJaxWsClientProxy proxy = (PlayJaxWsClientProxy) Proxy.getInvocationHandler(service);
HTTPConduit conduit = (HTTPConduit) proxy.getClient().getConduit();
TLSClientParameters tlsParams = new TLSClientParameters();
tlsParams.setSSLSocketFactory(sslContext.getSocketFactory());
conduit.setTlsClientParameters(tlsParams);
// Invoke any method of SOAP service
service.method(...);
```

**Comment by ihostage** [comment]
I think, that we can close this issue. @alexduros what you think? 😄

**Comment by alexduros** [comment]
@ihostage thanks for your reply. and yes, I think we can now close this issue.
