### ISSUE TITLE
can't pull sbt plugin Scala 2.12 based project

### ISSUE THREAD

**Issue by ferhtaydn** [playframework/play-soap#38]
Hi @marcospereira,

I can't add sbt plugin to the project whose scalaVersion is 2.12.3.
play-soap-client lives at OSS with mvn style, plugin lives at playframework's bintray with ivy style.

It should be useful to publish for Scala 2.12 also and provide a template or sample project to show how sbt plugin can be used without dependency unresolved pain.

Thanks,

**Comment by marcospereira** [comment]
Scala 2.12 version was just published:

https://repo1.maven.org/maven2/com/typesafe/play/play-soap-client_2.12/1.1.4/

Instructions to use the plugins without unresolved problems are here:

https://github.com/playframework/play-soap#installation

I'm a little short of time now but appreciate any help to create a sample project that shows how to use the plugin.

Best.
