### ISSUE TITLE
Provide an option to pretty log the payload ?

### ISSUE THREAD

**Issue by catflyflyfly** [playframework/play-soap#44]
Hiya, I'm trying to log both inbound and outbound message which pass through the client. I've set the `debugLog` option to `true`. However, the payload printed is a chuck of xml and I can't set cxf Interceptor (in PlaySoapClient.createPort) prettyLogging to true since only createPort method is exposed. What should I do ?

**Comment by tilmanginzel** [comment]
@CatFlyFlyFly You can find some documentation on how to achieve this with a `SOAPHandler` here: https://playframework.github.io/play-soap/Handlers.html
