### ISSUE TITLE
Support Scala 2.13

### ISSUE THREAD

**Issue by ihostage** [playframework/play-soap#54]
Plus revert support Scala 2.11 for SOAP client

**Comment by sergiuszkierat** [comment]
@ihostage any news about [1.1.5](https://github.com/playframework/play-soap/milestone/1)?

**Comment by ihostage** [comment]
@sergiuszkierat You can to use the SNAPSHOTS version now. https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-soap-client_2.13/
We plan to publish `1.1.5` version with Travis CI. But we have a problem with #89 and I need time to resolve it.

**Comment by lapidus79** [comment]
Anything that can be done to speed up the release of 1.1.5?

**Comment by ihostage** [comment]
Hi, @lapidus79! 👋 
I'm waiting too 🤷‍♂ When somebody from Lightbend will change credentials on my PR, I will publish a release `1.1.5`. But folks are busy now. 😞

**Comment by lapidus79** [comment]
Excuse me the n00b question. But how can I take into use the snapshot version. What is correct address for the sbt-play-soap snapshot.
eg.
addSbtPlugin("com.typesafe.sbt" % "sbt-play-soap" % "1.1.4")

**Comment by sergiuszkierat** [comment]
@lapidus79, you could try with 
```
addSbtPlugin(
  "com.typesafe.play" % "play-soap-client_2.13" % "1.1.4+162-d80330d5-SNAPSHOT" from "https://oss.sonatype.org/content/repositories/snapshots/com/typesafe/play/play-soap-client_2.13/1.1.4+162-d80330d5-SNAPSHOT/play-soap-client_2.13-1.1.4+162-d80330d5-SNAPSHOT.jar"
)
```
